spring:
  application:
    name: ms-matricula

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ms_matricula?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 7569

# URL del ms-cursos para Feign (si no usas Eureka para resolverlo)
cursos:
  base-url: http://localhost:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
  instance:
    hostname: localhost